version: "3.8"

services:

  postgres:
    container_name: postgres_sealed
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sealed_user
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: sealed_db

    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
